const myData = [
  {
    id: 1,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    h1: "Our state of the art Angiography Suite is used as a show piece by Siemens for the Asia Pacific region.",
    h2: "Procedures performed in the Angiography Suite include:",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634617000/pexels-tara-winstead-7723607_vxudoh.jpg",
    name: "Breast Centre",
    h1: "A comprehensive range of medical imaging facilities is available including:",
    p2: "stereotactic mammography",
    p3: "high-resolution ultrasound",
    p4: "biopsies",
    p5: "C.T.",
    p6: "nuclear medicine",
    p7: "M.R.I.",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634617537/pexels-towfiqu-barbhuiya-9099821_tv6ce3.jpg",
    name: "Cardiac Unit",
    h1: "The Cardiac Unit has 28 private rooms and is comprised of 10 acute Coronary Care beds and 18 cardiac ward beds with the ability to centrally monitor all patients.",
    h2: "Cardiologists from GenesisCare and other practices across the state admit patients to the St Andrew's Unit.",
    h3: "The Cardiac Unit is an integral part of the ‘Cardiac Centre of Excellence’ that provides care to patients undergoing investigational and interventional cardiology procedures such as",
    p1: "Coronary Angiography",
    p2: "Percutaneous Coronary Intervention",
    p3: "Device Implantation (PPM and AICD)",
    p4: "Arrhythmia Ablation",
    p5: "Electrophysiological Studies and investigations.",
    p6: "TAVI",
    p7: "Carotid Angiogram & Angioplasty / Stent",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634617688/pexels-pixabay-236380_brqnav.jpg",
    name: "Critical Care Unit",
    h1: "The Critical Care Unit (CCU) is one of the best-designed acute care facilities in the state, combining Intensive and High-Dependency Care. Consisting of 18 centrally monitored beds, the CCU provides care for patients with a broad range of medical and surgical conditions.  The medical and nursing staff within the Unit provide care for patient's undergoing major surgery such as cardiothoracic and robotic procedures or those requiring high level medical care.",
    h2: "The state-of-the-art intensive care facility is capable of providing all modalities of support for critically ill patients, including:",
    p1: "mechanical ventilation",
    p2: "invasive monitoring",
    p3: "continuous haemodialysis",
    p4: "The CCU is located on the first floor, and is in close proximity to the operating theatres, recovery unit, angiography suite and radiology services.",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634637609/cmccFull-300-899x600_smy5le.jpg",
    name: "Radiology & Imagery",
    h1: "Dr Jones & Partners provide a comprehensive medical imaging service based at the South Terrace campus. The Practice offers a complete range of procedures including:",
    p1: "X-rays",
    p2: "Ultrasound",
    p3: "CT scanning",
    p4: "Mammography",
    p5: "Nuclear medicine",
    p6: "MRI",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634618333/pexels-mikhail-nilov-8942521_ft3q02.jpg",
    name: "Emergency Service",
    h1: "St Andrew's Hospital Emergency Service provides emergency medical attention from 8.00am - 10.00pm, seven days a week.",
    h2: "The Emergency Service has been established to provide assessment of patients with acute medical and surgical conditions who:",
    p1: "require emergency care",
    p2: "have a local doctor / specialist referral",
    p3: "have been a recent inpatient and require review",

    h3: "We pride ourselves on having a medical and nursing team that boasts the experience and necessary training to provide one of the best emergency care services in South Australia. This level of expertise not only means a higher quality of care but it has a positive impact on waiting times. In fact, waiting times are generally much, much less than those experienced in the emergency departments of public hospitals.",
    p5: "Entry to the Emergency Service is via the front entrance at 350 South Terrace and short term car parking is available.",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
    p5: "Implantable Cardiovertor Defibrillator (ICD)",
    p6: "Femoral Angiogram & Angioplasty",
    p7: "Carotid Angiogram & Angioplasty / Stent",
    p8: "Endoluminal Stent Graft Insertion",
    p9: "Embolisations of bleeding vessels",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
    p5: "Implantable Cardiovertor Defibrillator (ICD)",
    p6: "Femoral Angiogram & Angioplasty",
    p7: "Carotid Angiogram & Angioplasty / Stent",
    p8: "Endoluminal Stent Graft Insertion",
    p9: "Embolisations of bleeding vessels",
  },
];
export default myData;
