const myData = [
  {
    id: 1,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
    p5: "Implantable Cardiovertor Defibrillator (ICD)",
    p6: "Femoral Angiogram & Angioplasty",
    p7: "Carotid Angiogram & Angioplasty / Stent",
    p8: "Endoluminal Stent Graft Insertion",
    p9: "Embolisations of bleeding vessels",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634617000/pexels-tara-winstead-7723607_vxudoh.jpg",
    name: "Breast Centre",
    p1: "A comprehensive range of medical imaging facilities is available including:",
    p2: "stereotactic mammography",
    p3: "high-resolution ultrasound",
    p4: "biopsies",
    p5: "C.T.",
    p6: "nuclear medicine",
    p7: "M.R.I.",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
    p5: "Implantable Cardiovertor Defibrillator (ICD)",
    p6: "Femoral Angiogram & Angioplasty",
    p7: "Carotid Angiogram & Angioplasty / Stent",
    p8: "Endoluminal Stent Graft Insertion",
    p9: "Embolisations of bleeding vessels",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
    p5: "Implantable Cardiovertor Defibrillator (ICD)",
    p6: "Femoral Angiogram & Angioplasty",
    p7: "Carotid Angiogram & Angioplasty / Stent",
    p8: "Endoluminal Stent Graft Insertion",
    p9: "Embolisations of bleeding vessels",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
    p5: "Implantable Cardiovertor Defibrillator (ICD)",
    p6: "Femoral Angiogram & Angioplasty",
    p7: "Carotid Angiogram & Angioplasty / Stent",
    p8: "Endoluminal Stent Graft Insertion",
    p9: "Embolisations of bleeding vessels",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
    p5: "Implantable Cardiovertor Defibrillator (ICD)",
    p6: "Femoral Angiogram & Angioplasty",
    p7: "Carotid Angiogram & Angioplasty / Stent",
    p8: "Endoluminal Stent Graft Insertion",
    p9: "Embolisations of bleeding vessels",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
    p5: "Implantable Cardiovertor Defibrillator (ICD)",
    p6: "Femoral Angiogram & Angioplasty",
    p7: "Carotid Angiogram & Angioplasty / Stent",
    p8: "Endoluminal Stent Graft Insertion",
    p9: "Embolisations of bleeding vessels",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/abidazad/image/upload/v1634580630/coronary-angiography-suite-simon-fraserfreeman-hospital-newcastleupon-tynescience-photo-library_w80gck.jpg",
    name: "Angiography",
    p1: "Procedures performed in the Angiography Suite include:",
    p2: "Coronary Angiogram",
    p3: "Coronary Angioplasty & Stent Insertion",
    p4: "Permanent Pacemaker Insertion (PPM)",
    p5: "Implantable Cardiovertor Defibrillator (ICD)",
    p6: "Femoral Angiogram & Angioplasty",
    p7: "Carotid Angiogram & Angioplasty / Stent",
    p8: "Endoluminal Stent Graft Insertion",
    p9: "Embolisations of bleeding vessels",
  },
];
export default myData;
